version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Flask Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # React Dockerfile
    ports:
      - "3000:3000"
